### ISSUE TITLE
Draft Resolution for the adoption of Google Forms for voting on Board Resolutions

### ISSUE THREAD

**Issue by SteveReiter** [devedmonton/devedmonton-org#1]
We need to draft a resolution for voting with google forms.

Please review the draft resolution on google docs and add comments.

https://docs.google.com/document/d/1yjdETWiL5-T9Is3nr8ojhsFpvnwvK1Xp5rYrS3oAlBI/edit?usp=sharing

**Comment by abramhindle** [comment]
The draft looks fine, but who has the github sponsorship for the organization? Did we get a free account?

**Comment by MarkBennett** [comment]
> The draft looks fine, but who has the github sponsorship for the organization? Did we get a free account?

Yes. The organisation has a free plan. If we need to go over it then we can expense a paid plan but I don't see us having a large set of private repos, especially to begin.

**Comment by benzittlau** [comment]
Is this resolution valid if we vote for it using google forms before we've passed a resolution on voting using google forms?  Half joking, but half not.

**Comment by benzittlau** [comment]
Resolution itself looks good to me.

**Comment by Estyn** [comment]
Looks good to me as well.

**Comment by SteveReiter** [comment]
@benzittlau  There is nothing in our bylaws about exactly how we vote so in theory we could use a different method for every resolution. It only becomes an issue if there's any kind of legal challenge, I think as long as this passes unanimously and there is a way to verify the identity of each voter then we should be fine in that regard.

**Comment by SteveReiter** [comment]
Resolution has been created and is up for voting: https://goo.gl/forms/rReYj1VLEUJa6LkK2
