### ISSUE TITLE
Finish mission statement

### ISSUE THREAD

**Issue by SteveReiter** [devedmonton/devedmonton-org#14]
Get everyone on the board to answer the 4 mission statement questions referencing the values identified during the kickoff meeting.

Why do we exist?
What do we do?
How do we do it?
How do we behave?

Values
- Collaborative
- Transparent
- Deliver Iteratively
- Targeted Focus
- Impact
- Optimistic
- Approachable / Inclusive / Open / Diverse
- Aware and Responsive
- Support through Empowerment
- Increase Impact not reduce work
- Visible / Integrated with the community
- Agile / Lean processes
- Unbiased
- Credible and accountable

**Comment by MarkBennett** [comment]
We should wrap this up, as it's going to come up more over the next while and we need to have a clear focus. Right now, everyone but @Estyn and @ashiazed have added a draft of the mission statement to:

https://docs.google.com/document/d/1z2Z91mr9b2UE8SBB90rqvIGJ9dxghDUncM9K684TG40/edit#

Why don't we setup a call or hangout to hash this out once @ashiazed is back from vacation on the 25th? We could also stand to sync up on our other tasks before September hits.

**Comment by MarkBennett** [comment]
Here's all the mission statements we've recieved:

> To fuel the growth of an inclusive, welcoming, and impactful developer community in Edmonton by supporting leaders, mentoring and empowering new contributors, and promoting collaboration across skill-levels and disciplines.

> Edmonton has world class software development talent that is underrated nationally and internationally. We hope to grow the supportive and diverse development community while maintaining it’s humble and accessible nature.

> Technology is fast paced, 3 years for a technology can be long to cover its introduction through to its discontinuation. Technology-based meetup groups face these challenges and more. Developer meetups face issues of sponsorship, promotion and advertising, catering, MCing, finding speakers. These meetup groups often share the same tasks and have the same requirements. Thus Dev Edmonton proposes to provide support to these meetups in terms of enabling sponsorship via provisioning of financial tools, cross-promoting meetups within the Edmonton developer community, and providing a hub from which new meetups may spring.
>
> Dev Edmonton seeks to act as an umbrella society to provide tools, structure, and act as a legal entity, to foster developer oriented meetups.

> Dev Edmonton is a society of developers, designers, entrepreneurs, and citizens living in Edmonton who believe a propesous, welcoming, and impactful development community is of value to all. We act with mindfulness, optimism, and passion to forward this vision by igniting new opportunity, empowering existing capacity, and connecting the development community with itself and the with Edmonton at large. 

> To foster an integrated, open and diverse developer community in Edmonton by promoting collaboration between local groups, sharing support and resources and establishing relationships and opportunities to work together to increase our impact.

**Comment by MarkBennett** [comment]
Here's what I'm proposing for our mission statement:

Dev Edmonton is a society of technologists, entrepreneurs and citizens living in Edmonton who believe a prosperous, diverse, and accessible development community enriches us all. We work openly and in partnership with local meetups, corporations, educational institutions, and the broader community to **collectively solve common challenges**, identify and **address gaps in technical capacity**, **connect and promote** events and initiatives, and provide an institution to **nurture and support technology meetups and organizations throughout their lifetime**.

It provides reasonable answers to the questions Ben proposed and is specific about what we do, and don't.

Feedback welcome!

**Comment by SteveReiter** [comment]
"We work openly and in partnership with local meetups, corporations, educational institutions, and the broader community..." what about government (probably the city mostly or EEDC) do we plan to interact/work with them?

"identify and address gaps in technical capacity" feels like it might be too open ended to me but not sure.

**Comment by benzittlau** [comment]
What would the relationship between the mission statement and the 4 questions be?

**Comment by MarkBennett** [comment]
> What would the relationship between the mission statement and the 4 questions be?

@benzittlau the mission statement is meant to clearly define who we are, what we do and don't do, and why. I think that would cover the 4 questions at the top of this thread.

It should be short enough that it's easy to read and understand even if you don't know anything about the society itself, but detailed enough that reading it would give you a sense of our purpose, priorities, and objectives.

It shouldn't be as detailed as a strategic plan where we're trying to break down large objectives into specific time frames and action items, but it also doesn't need to be short enough to fit on a letter heard or anything like that.

I also like to think that having some kind of big ambitious goal in the mission is a nice way to rally people together but again, you don't want to make it too long.

**Comment by MarkBennett** [comment]
> "We work openly and in partnership with local meetups, corporations, educational institutions, and the broader community..." what about government (probably the city mostly or EEDC) do we plan to interact/work with them?

Government would be considered part of the broader community. I think we'd want it to be clear that this list isn't exhaustive. Part of me is wondering if we should really list them all in the mission statement.

**Comment by MarkBennett** [comment]
Alright, here's another go based off our Slack conversations...

> Dev Edmonton is a society of citizens who believe world class technology can grow and thrive in Edmonton, and that a prosperous, diverse, and accessible development community enriches us all. We realize this vision by sharing resources and knowledge, addressing gaps in technical capacity, connecting and promoting events and initiatives, and providing an institution to support technology meetups and organizations.

**Comment by MarkBennett** [comment]
Here's the latest copy we're working with on Slack:

> Dev Edmonton Society is made up of people who believe world class technology can grow and thrive in Edmonton, and that a prosperous, diverse, and collaborative development community enriches us all. We realize this vision by sharing resources and knowledge, understanding the big picture, inspiring/developing new and existing skills and technologies, promoting events and initiatives, and providing an institution supporting technology meetups and organizations.

/cc @abramhindle 

We're talking about getting "impacting the big-picture" in there but want to make sure it's specific enough to make sense.

**Comment by MarkBennett** [comment]
Updating again:

> Dev Edmonton Society is made up of people who believe that an *impactful*, *diverse*, and *collaborative* developer community enriches us all. We realize this vision by *sharing* knowledge and ideas, *understanding* the community and its needs, *promoting* events and initiatives, and *supporting* technology meetups and organizations.

**Comment by MarkBennett** [comment]
As per board resolution 0005, Dev Edmonton Society has adopted the following as our mission:

> Dev Edmonton Society is made up of people who believe that an impactful, diverse, and collaborative developer community enriches us all. We realize this vision by sharing knowledge and ideas, understanding the community and its needs, promoting events and initiatives, and supporting technology meetups and organizations.

Closing.
