### ISSUE TITLE
Meet face-to-face to kick off society

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/devedmonton-org#2]
**WHAT**: A meeting to kick-off the next year of the Dev Edmonton Society
**WHEN**: Saturday July 14th, 10:00am-1:00pm
**WHERE**: Jobber Offices, 10520 Jasper Ave, Edmonton, AB T5J 1Z7

We'll start with coffee and brainstorming then wrap with lunch.

# Deliverables

* [ ] Mission Statement
  * Who we are, what we're doing, why and how
* [ ] Upcoming Milestones
  * e.g. a fixed cycle, a given set of accomplishments, a given date, other indicator of completion)
  * at least 2 milestones, perhaps more
* [ ] Strategic Plan
  * Broken into milestones
  * A list of specific objectives each tied to one or more goals
  * Each goal has one or more success criteria, one or more implementation steps, and ideally an owner

# Agenda (3 Hours Total)

* Opening notes and summary of current status (5 minutes)
* Introductions (15 minutes)
* Review our survey questions (20 minutes)
* COFFEE BREAK (10 minutes)
* Brainstorm what we see the society doing? (20 minutes)
  * What would the worst version of the Dev Edmonton Society look like? (5 minutes)
  * What about the best? (15 minutes)
* Agree on a mission statement (30 minutes)
* BREAK TO GRAB LUNCH (10 minutes)
* Agree on upcoming milestones (10 minutes)
* Identify objectives for next two milestones (20 minutes)
* Develop strategic plan with breakdowns for objectives in next milestone (20 minutes)
* Wrap up and next steps (10 minutes)

* Bonus Items (Should time allow)
  * Breakdown subsequent milestone
  * Agree on a data sharing policy (open and share by default?)
  * Code of Conduct
  * Shared calendar for scheduling events?

**Comment by SteveReiter** [comment]
I think this falls under mission and vision but maybe warrants a separate bullet point. I don't like high level mission statements on their own, I think it is far more useful if backed by some high level 'how do we do it' type of statements.

Say the mission was something like "Help develop a strong development community in Edmonton", I think it's good to back that with statements like "By supporting developer meetups", "by building relationships with companies in the industry", etc.

**Comment by abramhindle** [comment]
I'll be back in August. Don't wait up for me. Japan makes interaction really awkward.

**Comment by MarkBennett** [comment]
> I'll be back in August. Don't wait up for me. Japan makes interaction really awkward.

Ok. We should definitely find a good time to catch up once you're back. Hope you're enjoying Japan!

**Comment by MarkBennett** [comment]
> I think this falls under mission and vision but maybe warrants a separate bullet point. I don't like high level mission statements on their own, I think it is far more useful if backed by some high level 'how do we do it' type of statements.
> 
> Say the mission was something like "Help develop a strong development community in Edmonton", I think it's good to back that with statements like "By supporting developer meetups", "by building relationships with companies in the industry", etc.

We had a process we used to develop a framework for the Ruby meetup that worked really well. It was quite a while ago, but I remember I got it from a book by the Ubuntu crew. I'll see if I can track it down and find me copy.

**Comment by MarkBennett** [comment]
Found it! It's from a book called the [Art of Community Building by Jono Bacon](https://www.amazon.ca/dp/B008224FMC/ref=pe_386430_122412850_TE_DP). I'm just refreshing myself right now, then I do up a summary that we can add to the agenda. He was the Ubuntu community manager for a long time, and the book walks through the process they used to open source building their organisational plan, as well as taking that plan and executing it in an open source way using open tooling and processes.

**Comment by MarkBennett** [comment]
So just to keep this thread current I've added details about meeting time to the description.

I'm thinking it might make sense to do a brief survey and answer some questions before hand, then focus on using our meeting time to find concensus and agree on next steps for the society. I'll try to get together a survey that achieves this and send it out for review by Monday morning.

**Comment by MarkBennett** [comment]
Survey is done. I've sent this to everyone on Slack, but you can find it here:

https://docs.google.com/forms/d/e/1FAIpQLSd_8LktpI5S9yXxCg8KH3_NdgMONLpXbXbtjDNrSNispT-b6Q/viewform?usp=sf_link

I've also updated the agenda for Saturday. It's going to be packed so I'm thinking we should plan on ordering in and working through lunch if everyone is ok with that?
