### ISSUE TITLE
Setup a Slack bot to great new members

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/devedmonton-org#26]
We'll want a way to respond to the [Slack team_join event](https://api.slack.com/events/team_join) and send a private message welcoming the new member along with details about:

* the purpose of the slack
* how to introduce themselves
* how to find and create channels
* the code of conduct

**Comment by MarkBennett** [comment]
As per @ashiazed, we should look at trying:

http://greetbot.io/

Thanks for the catch @benzittlau.

**Comment by SteveReiter** [comment]
Can we close this? I think the greetbot is setup.

**Comment by MarkBennett** [comment]
Closing. We can open a new issue if we find deficiencies.
