### ISSUE TITLE
Draft resolution to adopt GitHub for project managment

### ISSUE THREAD

**Issue by SteveReiter** [devedmonton/devedmonton-org#3]
https://docs.google.com/document/d/1M5NH6snez0Tuydmri9Z-sM2taXRVzFzWkCJI0GUliMg/edit?usp=sharing

**Comment by benzittlau** [comment]
LGTM (Looks good to me)

**Comment by Estyn** [comment]
Looks good.

**Comment by SteveReiter** [comment]
Resolution has been created and is up for voting: https://goo.gl/forms/EIemvpZqdHPOYVVn2
