### ISSUE TITLE
April board meeting

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/devedmonton-org#36]
**WHAT:** April 2019 Dev Edmonton Board Meeting
**WHEN:** April 24th 18:30-22:00
**WHERE:** Unit B, McKenney Bldg. 10187 104 ST NW Edmonton, AB T5J0Z9

Time for another board meeting! Add some items to the agenda below and we'll go through them. Put your name beside the items you've added so we know who's driving them.

# Agenda
* Year-End (@Estyn are you able to quarterback this as it's financials left? I can help))
* Bringing in members / member agreement (@benzittlau, can you handle this one?)
* Bringing more meetups on board in September (@MarkBennett)
* Meetup Meetup (@MarkBennett)
* Website / social media strategy (TBD* Engaging / empowering members
* Start a marketing effort to promote and advocate for local development community (@SteveReiter can you elaborate?)
* Budgetting for the next year
  * what requires a budget? (book keeping, year end, hosting, diversity projects, A/V resources, promotional material, meetup organizer material prep)
  * what sources of income are available? (memberships, sponsorships, donations (patreaon / opencollective?), selling Dev Edmonton swag)
  * does the distribution of this budget align with our mission?
* How do we start generating money in to support our objectives?

# TODO
* Pick venue (@MarkBennett witll put out some dates, then find a venue)
* Add past items

**Comment by SteveReiter** [comment]
I'd like to add/modify one agenda item, I'd like to discuss getting someone on board in a Marketing/PR role. There have been news articles about software development in Edmonton with quotes from organizations doing a lot less for the community and industry, I think we should work on increasing our profile.

**Comment by MarkBennett** [comment]
> I'd like to add/modify one agenda item, I'd like to discuss getting someone on board in a Marketing/PR role. There have been news articles about software development in Edmonton with quotes from organizations doing a lot less for the community and industry, I think we should work on increasing our profile.

Great idea @SteveReiter! Can you edit the agenda in the description about and add that so we don't forget? Thanks!

**Comment by NonMint** [comment]
I think that's sort an intrinsic discussion to the website and social media strategy. All of those elements roll together into a PR/Visibility part of Dev Edmonton. What do we want to say, how do we want to say it, and most importantly, how do we amplify the voices of our members.

**Comment by MarkBennett** [comment]
> I think that's sort an intrinsic discussion to the website and social media strategy. All of those elements roll together into a PR/Visibility part of Dev Edmonton. What do we want to say, how do we want to say it, and most importantly, how do we amplify the voices of our members.

For sure. Anyone who's visited our website right now has probably noticed it's sorely lacking in details and content. It would be a great place to start more clearly sharing what we do and who we represent. We'll probably need to set time aside to come up with clear content to include as I'm guessing that will take the longest time to develop and get agreement on. Once we've got that I'm thinking the actual design and production should go fairly quickly.

I'd like to keep this issue focused on the meeting itself, but it would be good to have some of this discussion before the meeting. I've created issue #37 and we can carry this discussion on more there @SteveReiter, @NonMint, et al.

**Comment by dgmouris** [comment]
Mind if I join in on this meeting @MarkBennett and others? I'd love to help in any way that you folks need it!

**Comment by MarkBennett** [comment]
> Mind if I join in on this meeting @MarkBennett and others? I'd love to help in any way that you folks need it!

Would be great to have you @dgmouris! 👍

**Comment by ashiazed** [comment]
Please add major focus topics to the agenda. I'm hoping we can gather groups around focus topics and have people engage in small tasks that help as well as larger chunks for those who are able.

**Comment by MarkBennett** [comment]
I added some discussion around budgetting and sources of revenue. I'd like to produce a draft budget we can refine after the board meeting and bring to sponsors and the membership.

**Comment by MarkBennett** [comment]
Just added the location. We're going to use @JasPanesar's co-working space, called Unit B for this one.

Any interest in ordering food or do we want to try to wrap by 8:00 and grab a bite after like we did last time?

**Comment by MarkBennett** [comment]
Closing this as the board meeting is over. @SteveReiter can you post a link to the minutes when you, have a minute. ;)
