### ISSUE TITLE
Collect funds owed to Exchangejs - Jobber (Ben)

### ISSUE THREAD

**Issue by SteveReiter** [devedmonton/devedmonton-org#9]
Jobber committed to sponsoring Exchangejs in 2017 but funds were not collected due to waiting for the establishment of Dev Edmonton.

**Comment by SteveReiter** [comment]
Blocked by #4

**Comment by benzittlau** [comment]
I have received the Invoice for this and passed it on to Darren, who will be cutting a cheque right away.  Should be available by end of week at the latest.

**Comment by MarkBennett** [comment]
Thanks @benzittlau!

**Comment by MarkBennett** [comment]
Money recieved in November. Closing.
